schema_version = "1.0.0"

id = "modifiers_toolbox"
version = "1.1.1"
name = "Modifiers Toolbox"
tagline = "Improved workflow in modifiers stack"
maintainer = "carlosmu | carlos.damian.munoz@gmail.com"
type = "add-on"
tags = ["Modeling", "User Interface"]
website = "https://blendermarket.com/products/modifiers-toolbox"

blender_version_min = "4.0.0"
license = ["SPDX:GPL-3.0-or-later",]